services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./scripts/grafana/provisioning
        target: /etc/grafana/provisioning
      - type: bind
        source: ./scripts/grafana/dashboards
        target: /etc/grafana/squeak-dashboards
      - type: volume
        source: grafana_data
        target: /var/lib/grafana

  fluentbit:
    image: fluent/fluent-bit:3.1.9
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - type: bind
        source: ./scripts/fluentbit/fluent-bit.conf
        target: /fluent-bit/etc/fluent-bit.conf

  loki:
    image: grafana/loki:3.2.1
    ports:
      - "3100:3100"
    volumes:
      - ./scripts/loki:/etc/loki
    command: -config.file=/etc/loki/config.yaml

  redis:
    image: redis:7.4.1-alpine
    ports:
      - 6379:6379

  web:
    build: .
    ports:
      - 80:80
    depends_on:
      redis:
        condition: service_started
      fluentbit:
        condition: service_started
    environment:
      - REDIS_URL=redis:6379
    logging:
      driver: fluentd
      options:
        tag: http-service
        fluentd-sub-second-precision: "true"

volumes:
  grafana_data:
