services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./scripts/grafana/provisioning
        target: /etc/grafana/provisioning
      - type: bind
        source: ./scripts/grafana/dashboards
        target: /etc/grafana/squeak-dashboards
      - type: volume
        source: grafana_data
        target: /var/lib/grafana

volumes:
  grafana_data:
