// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
